package com.example;

import eu.verdelhan.ta4j.Decimal;
import eu.verdelhan.ta4j.Tick;
import eu.verdelhan.ta4j.TimeSeries;
import eu.verdelhan.ta4j.indicators.simple.ClosePriceIndicator;
import eu.verdelhan.ta4j.indicators.trackers.RSIIndicator;
import org.joda.time.DateTime;
import yahoofinance.Stock;
import yahoofinance.YahooFinance;
import yahoofinance.histquotes.HistoricalQuote;
import yahoofinance.histquotes.Interval;

import java.io.IOException;
import java.util.Arrays;
import java.util.Calendar;
import java.util.List;
import java.util.stream.Collectors;

public class TajApplication {

    public static void main(String[] args) throws IOException {

        final List<String> filtered = Arrays.asList(getTokens()).parallelStream()
                .filter(symbol -> {
                    TimeSeries series = null;
                    try {
                        series = getTimeSeries(symbol.trim(), Calendar.getInstance());
                        final RSIIndicator rsiIndicator = getRsiIndicator(series, 14);
                        return rsiIndicator.getValue(series.getEnd()).isGreaterThan(Decimal.valueOf(70d));
                    } catch (Exception e) {
                        return false;
                    }
                }).collect(Collectors.toList());

        filtered.forEach(System.out::println);
    }

    public static RSIIndicator getRsiIndicator(TimeSeries series, int rsiPeriod) {
        return new RSIIndicator(new ClosePriceIndicator(series), rsiPeriod);
    }

    public static TimeSeries getTimeSeries(String ticker, Calendar currentDate) throws IOException {
        final String symbol = ticker;
        Calendar from = Calendar.getInstance();
        from.add(Calendar.MONTH, -2); // from at least 1 year ago
        Stock stock = YahooFinance.get(symbol);
        List<HistoricalQuote> googleHistQuotes = stock.getHistory(from, currentDate, Interval.DAILY);
        final List<Tick> ticks = googleHistQuotes.stream().map(quote -> new Tick(new DateTime(quote.getDate().getTime()), quote.getOpen().doubleValue(),
                quote.getHigh().doubleValue(),
                quote.getLow().doubleValue(),
                quote.getClose().doubleValue(), quote.getVolume())).sorted((t1, t2) -> t1.getEndTime().compareTo(t2.getEndTime()))
                .collect(Collectors.toList());
        return new TimeSeries(symbol + "-series", ticks);
    }

    public static String[] getTokens() {
        String scrips =
                "3IINFOTEC.NS\n" +
                        "ADVANIHOT.NS\n" +
                        "AICHAMP.NS\n" +
                        "ALLSEC.NS\n" +
                        "ALPHAGEO.NS\n" +
                        "ALPINEHOU.NS\n" +
                        "AMARJOTHI.NS\n" +
                        "AMLSTEEL.NS\n" +
                        "ANKURDRUG.NS\n" +
                        "ANTGRAPHI.NS\n" +
                        "ARIHANT.NS\n" +
                        "ARROWTEX.NS\n" +
                        "ASHAPURMI.NS\n" +
                        "ASHCONIUL.NS\n" +
                        "ASHIMASYN.NS\n" +
                        "ASIANELEC.NS\n" +
                        "ASIL.NS\n" +
                        "AUSOMENT.NS\n" +
                        "AUSTRAL.NS\n" +
                        "BAGFILMS.NS\n" +
                        "BANARBEAD.NS\n" +
                        "BANG.NS\n" +
                        "BEARDSELL.NS\n" +
                        "BEDMUTHA.NS\n" +
                        "BILPOWER.NS\n" +
                        "BIRLACOT.NS\n" +
                        "BLBLIMITE.NS\n" +
                        "BLUECOAST.NS\n" +
                        "BODALCHEM.NS\n" +
                        "BODHTREE.NS\n" +
                        "BROOKS.NS\n" +
                        "CALSOFT.NS\n" +
                        "CCCL.NS\n" +
                        "CELESTIAL.NS\n" +
                        "CHESLINTE.NS\n" +
                        "CINEVISTA.NS\n" +
                        "CLUTCHAUT.NS\n" +
                        "COROENGG.NS\n" +
                        "CURATECH.NS\n" +
                        "CYBERMEDI.NS\n" +
                        "DBREALTY.NS\n" +
                        "DECOLIGHT.NS\n" +
                        "DELTAMAGN.NS\n" +
                        "DHANUS.NS\n" +
                        "DHUNINV.NS\n" +
                        "DSSL.NS\n" +
                        "DWARKESH.NS\n" +
                        "EDSERV.NS\n" +
                        "ELECTHERM.NS\n" +
                        "ELNET.NS\n" +
                        "EMAMIINFR.NS\n" +
                        "EMKAY.NS\n" +
                        "EMPEESUG.NS\n" +
                        "ENTEGRA.NS\n" +
                        "EUROCERA.NS\n" +
                        "FCSSOFT.NS\n" +
                        "GANGOTRI.NS\n" +
                        "GISOLUTIO.NS\n" +
                        "GKWLIMITE.NS\n" +
                        "GLFL.NS\n" +
                        "GUFICBIO.NS\n" +
                        "GUJSTATFI.NS\n" +
                        "HBLPOWER.NS\n" +
                        "HINDMOTOR.NS\n" +
                        "HINDSYNTE.NS\n" +
                        "HITACHIHO.NS\n" +
                        "HOTELRUGB.NS\n" +
                        "IBSEC.NS\n" +
                        "IITL.NS\n" +
                        "INDOSOLAR.NS\n" +
                        "INFINITE.NS\n" +
                        "INFODRIVE.NS\n" +
                        "IOLN.NS\n" +
                        "JAIBALAJI.NS\n" +
                        "JCTEL.NS\n" +
                        "JDORGOCHE.NS\n" +
                        "JEYPORE.NS\n" +
                        "JUPITER.NS\n" +
                        "KALYANIFR.NS\n" +
                        "KANANIIND.NS\n" +
                        "KANDAGIRI.NS\n" +
                        "KARMAENG.NS\n" +
                        "KARURKCP.NS\n" +
                        "KAUSHALYA.NS\n" +
                        "KESARENT.NS\n" +
                        "KEYCORPSE.NS\n" +
                        "KHAITANLT.NS\n" +
                        "KIRIINDUS.NS\n" +
                        "KLGSYSTEL.NS\n" +
                        "KOPDRUGS.NS\n" +
                        "KOTARISUG.NS\n" +
                        "KOVAI.NS\n" +
                        "KTIL.NS\n" +
                        "LAKSHMIFI.NS\n" +
                        "LIBERTSHO.NS\n" +
                        "LIQUIDBEE.NS\n" +
                        "LLOYDSTEE.NS\n" +
                        "LYKALABS.NS\n" +
                        "MAANALU.NS\n" +
                        "MALWACOTT.NS\n" +
                        "MARKSANS.NS\n" +
                        "MAWANASUG.NS\n" +
                        "MBSWITCH.NS\n" +
                        "MCDHOLDIN.NS\n" +
                        "MELSTAR.NS\n" +
                        "MINDACORP.NS\n" +
                        "MORARJETE.NS\n" +
                        "NAGREEKCA.NS\n" +
                        "NCOPPER.NS\n" +
                        "NEOCURE.NS\n" +
                        "NOL.NS\n" +
                        "NOVOPANIN.NS\n" +
                        "NUCENT.NS\n" +
                        "OSWALMIN.NS\n" +
                        "OUDHSUG.NS\n" +
                        "PANCHSHEE.NS\n" +
                        "PARRYSUGA.NS\n" +
                        "PATSPINLT.NS\n" +
                        "PEARLPOLY.NS\n" +
                        "PILANIINV.NS\n" +
                        "PIRLIFE.NS\n" +
                        "PRAENG.NS\n" +
                        "PRITHVISO.NS\n" +
                        "PVP.NS\n" +
                        "QUINTEGRA.NS\n" +
                        "RAIREKMOH.NS\n" +
                        "RAJSREESU.NS\n" +
                        "RAMKY.NS\n" +
                        "RANASUG.NS\n" +
                        "RANKLIN.NS\n" +
                        "REGENCERA.NS\n" +
                        "REISIXTEN.NS\n" +
                        "REMSONSIN.NS\n" +
                        "RMMIL.NS\n" +
                        "RPGLIFE.NS\n" +
                        "RSWM.NS\n" +
                        "SABERORGA.NS\n" +
                        "SAKHTISUG.NS\n" +
                        "SAKTHIFIN.NS\n" +
                        "SALONACOT.NS\n" +
                        "SAMBHAAV.NS\n" +
                        "SAMTEL.NS\n" +
                        "SARTHAKIN.NS\n" +
                        "SEZAL.NS\n" +
                        "SGFL.NS\n" +
                        "SGL.NS\n" +
                        "SHAHALLOY.NS\n" +
                        "SHALPAINT.NS\n" +
                        "SHANTIGEA.NS\n" +
                        "SHREYANIN.NS\n" +
                        "SHREYAS.NS\n" +
                        "SHRINATRA.NS\n" +
                        "SIL.NS\n" +
                        "SIMBHSUGA.NS\n" +
                        "SOMATEX.NS\n" +
                        "SPENTEX.NS\n" +
                        "SPLIL.NS\n" +
                        "SRGINFOTE.NS\n" +
                        "SRICHAMUN.NS\n" +
                        "STERLINBI.NS\n" +
                        "STINDIA.NS\n" +
                        "SUPERSPIN.NS\n" +
                        "SUPREMETE.NS\n" +
                        "SURANACOR.NS\n" +
                        "SURYAPHAR.NS\n" +
                        "TAINWALCH.NS\n" +
                        "TAKE.NS\n" +
                        "TAKSHEEL.NS\n" +
                        "TARAPUR.NS\n" +
                        "TCPLTD.NS\n" +
                        "TELEDATAI.NS\n" +
                        "TEXMOPIPE.NS\n" +
                        "THIRUSUGA.NS\n" +
                        "TIMESGTY.NS\n" +
                        "TNTELE.NS\n" +
                        "TRICOM.NS\n" +
                        "TTL.NS\n" +
                        "UMESLTD.NS\n" +
                        "UNIPLY.NS\n" +
                        "UNITEDTEA.NS\n" +
                        "UPERGANGE.NS\n" +
                        "UTTAMSUGA.NS\n" +
                        "V2RETAIL.NS\n" +
                        "VARDMNPOL.NS\n" +
                        "VARUN.NS\n" +
                        "VIMTALABS.NS\n" +
                        "VINYLINDI.NS\n" +
                        "VKSPL.NS\n" +
                        "VTMLTD.NS\n" +
                        "WALCHANNA.NS\n" +
                        "WEBELSOLA.NS\n" +
                        "WEIZFOREX.NS\n" +
                        "WELGLOB.NS\n" +
                        "WELPROJ.NS\n" +
                        "ZEENEWS.NS\n" +
                        "ZENITHEXP.NS\n" +
                        "AKSHOPTFB.NS\n" +
                        "ANGIND.NS\n" +
                        "ARCHIDPLY.NS\n" +
                        "AROGRANIT.NS\n" +
                        "ARSSINFRA.NS\n" +
                        "ASIANTILE.NS\n" +
                        "ATLASCYCL.NS\n" +
                        "BECREL.NS\n" +
                        "BGLOBAL.NS\n" +
                        "BHARATGEA.NS\n" +
                        "BILENERGY.NS\n" +
                        "BINDALAGR.NS\n" +
                        "BROADCAST.NS\n" +
                        "BSL.NS\n" +
                        "BVCL.NS\n" +
                        "CELEBRITY.NS\n" +
                        "CTE.NS\n" +
                        "CUBEXTUB.NS\n" +
                        "DCM.NS\n" +
                        "EASUNREYR.NS\n" +
                        "FAME.NS\n" +
                        "FARMAXIND.NS\n" +
                        "GKB.NS\n" +
                        "GOLDENTOB.NS\n" +
                        "GTNIND.NS\n" +
                        "GTNTEX.NS\n" +
                        "HALONIX.NS\n" +
                        "HBSTOCK.NS\n" +
                        "HEXATRADE.NS\n" +
                        "HILTON.NS\n" +
                        "HINDDORRO.NS\n" +
                        "IBWSL.NS\n" +
                        "ICIL.NS\n" +
                        "IFBAGRO.NS\n" +
                        "IGPL.NS\n" +
                        "IMPEXFERR.NS\n" +
                        "INDIANCAR.NS\n" +
                        "INVENTURE.NS\n" +
                        "IVP.NS\n" +
                        "IVRCLAH.NS\n" +
                        "JAINSTUDI.NS\n" +
                        "JIKIND.NS\n" +
                        "JINDWORLD.NS\n" +
                        "JUMBO.NS\n" +
                        "KAKATCEM.NS\n" +
                        "KHANDSE.NS\n" +
                        "KITPLYIND.NS\n" +
                        "KLRF.NS\n" +
                        "KRISHNAEN.NS\n" +
                        "KRITIIND.NS\n" +
                        "KSK.NS\n" +
                        "LUMAXAUTO.NS\n" +
                        "MAITHANAL.NS\n" +
                        "MALUPAPER.NS\n" +
                        "MANAPPURA.NS\n" +
                        "MANGLMCEM.NS\n" +
                        "MARALOVER.NS\n" +
                        "MUDRA.NS\n" +
                        "MUNJALAU.NS\n" +
                        "NCLIND.NS\n" +
                        "NEHAINT.NS\n" +
                        "NEOCORP.NS\n" +
                        "NEULANDLA.NS\n" +
                        "NSIL.NS\n" +
                        "NUTEK.NS\n" +
                        "PANASONIC.NS\n" +
                        "PARAL.NS\n" +
                        "PBAINFRA.NS\n" +
                        "PDUMJEIND.NS\n" +
                        "PEACOCKIN.NS\n" +
                        "PERIATEA.NS\n" +
                        "PGEL.NS\n" +
                        "PGIL.NS\n" +
                        "PIONDIST.NS\n" +
                        "PIONEEREM.NS\n" +
                        "POLARIND.NS\n" +
                        "PRICOL.NS\n" +
                        "PROVOGE.NS\n" +
                        "RAJRAYON.NS\n" +
                        "RASOYPR.NS\n" +
                        "REFEX.NS\n" +
                        "RSSOFTWAR.NS\n" +
                        "SANWARIA.NS\n" +
                        "SELMCL.NS\n" +
                        "SHILPI.NS\n" +
                        "SHIVAMAUT.NS\n" +
                        "SHIVTEX.NS\n" +
                        "SMOBILITY.NS\n" +
                        "SPYL.NS\n" +
                        "SRHHYPOLT.NS\n" +
                        "STARPAPER.NS\n" +
                        "STOREONE.NS\n" +
                        "SUJANATOW.NS\n" +
                        "SURYAJYOT.NS\n" +
                        "SWELECTES.NS\n" +
                        "TANFACIND.NS\n" +
                        "TCIFINANC.NS\n" +
                        "TFL.NS\n" +
                        "THINKSOFT.NS\n" +
                        "THOMASCOT.NS\n" +
                        "TIRUMALCH.NS\n" +
                        "VICEROY.NS\n" +
                        "VIJSHAN.NS\n" +
                        "VLSFINANC.NS\n" +
                        "WANBURY.NS\n" +
                        "WEIZMANIN.NS\n" +
                        "WELINV.NS\n" +
                        "WELSPUNIN.NS\n" +
                        "WINDMACHI.NS\n" +
                        "WINSOME.NS\n" +
                        "WSI.NS\n" +
                        "WWIL.NS\n" +
                        "ZEELEARN.NS\n" +
                        "ZENITHCOM.NS\n" +
                        "ZODJRDMKJ.NS\n" +
                        "20MICRONS.NS\n" +
                        "3MINDIA.NS\n" +
                        "A2ZMES.NS\n" +
                        "AANJANEYA.NS\n" +
                        "AARTIDRUG.NS\n" +
                        "AARTIIND.NS\n" +
                        "AARVEEDEN.NS\n" +
                        "ABBOTINDI.NS\n" +
                        "ABCIL.NS\n" +
                        "ABGSHIP.NS\n" +
                        "ABHISHEK.NS\n" +
                        "ACE.NS\n" +
                        "ACROPETAL.NS\n" +
                        "ADFFOODS.NS\n" +
                        "ADHUNIK.NS\n" +
                        "ADORWELD.NS\n" +
                        "ADSL.NS\n" +
                        "ADVANTA.NS\n" +
                        "AEGISCHEM.NS\n" +
                        "AFL.NS\n" +
                        "AFTEK.NS\n" +
                        "AGCNET.NS\n" +
                        "AGRODUTCH.NS\n" +
                        "AHLEAST.NS\n" +
                        "AHLUCONT.NS\n" +
                        "AHLWEST.NS\n" +
                        "AHMEDFORG.NS\n" +
                        "AIAENG.NS\n" +
                        "AJANTPHAR.NS\n" +
                        "AJMERA.NS\n" +
                        "AKZOINDIA.NS\n" +
                        "ALCHEM.NS\n" +
                        "ALEMBICLT.NS\n" +
                        "ALICON.NS\n" +
                        "ALKALI.NS\n" +
                        "ALKYLAMIN.NS\n" +
                        "ALLCARGO.NS\n" +
                        "ALMONDZ.NS\n" +
                        "ALPA.NS\n" +
                        "ALPSINDUS.NS\n" +
                        "ALSTOMT&D.NS\n" +
                        "AMAR.NS\n" +
                        "AMARAJABA.NS\n" +
                        "AMBIKCO.NS\n" +
                        "AMDIND.NS\n" +
                        "AMRUTANJA.NS\n" +
                        "AMTEKAUTO.NS\n" +
                        "AMTEKINDI.NS\n" +
                        "ANANTRAJ.NS\n" +
                        "ANDHRACEM.NS\n" +
                        "ANDHRSUGA.NS\n" +
                        "ANIKINDS.NS\n" +
                        "ANSALAPI.NS\n" +
                        "ANSALHSG.NS\n" +
                        "APARINDS.NS\n" +
                        "APCOTEXIN.NS\n" +
                        "APLAB.NS\n" +
                        "APLAPOLLO.NS\n" +
                        "APLLTD.NS\n" +
                        "APOLLOHOS.NS\n" +
                        "APPAPER.NS\n" +
                        "APTECHT.NS\n" +
                        "AQUA.NS\n" +
                        "ARCHIES.NS\n" +
                        "ARIES.NS\n" +
                        "ARSHIYA.NS\n" +
                        "ARVINDREM.NS\n" +
                        "ASAHIINDI.NS\n" +
                        "ASAHISONG.NS\n" +
                        "ASAL.NS\n" +
                        "ASHIANA.NS\n" +
                        "ASHOKA.NS\n" +
                        "ASIANHOTN.NS\n" +
                        "ASSAMCO.NS\n" +
                        "ASTEC.NS\n" +
                        "ASTERSILI.NS\n" +
                        "ASTRAL.NS\n" +
                        "ASTRAMICR.NS\n" +
                        "ASTRAZEN.NS\n" +
                        "ATFL.NS\n" +
                        "ATLANTA.NS\n" +
                        "ATNINTER.NS\n" +
                        "ATUL.NS\n" +
                        "AURIONPRO.NS\n" +
                        "AUTOAXLES.NS\n" +
                        "AUTOIND.NS\n" +
                        "AUTOLITIN.NS\n" +
                        "AVANTI.NS\n" +
                        "AVTNPL.NS\n" +
                        "AXISGOLD.NS\n" +
                        "AXIS-IT&T.NS\n" +
                        "BAJAJCORP.NS\n" +
                        "BAJAJELEC.NS\n" +
                        "BAJAJFINS.NS\n" +
                        "BAJFINANC.NS\n" +
                        "BALAJITEL.NS\n" +
                        "BALAMINES.NS\n" +
                        "BALKRISIN.NS\n" +
                        "BALLARPUR.NS\n" +
                        "BALMLAWRI.NS\n" +
                        "BALPHARMA.NS\n" +
                        "BANARISUG.NS\n" +
                        "BANCOINDI.NS\n" +
                        "BANKBEES.NS\n" +
                        "BANSWRAS.NS\n" +
                        "BARTRONIC.NS\n" +
                        "BASF.NS\n" +
                        "BASML.NS\n" +
                        "BAYERCROP.NS\n" +
                        "BBL.NS\n" +
                        "BBTC.NS\n" +
                        "BEPL.NS\n" +
                        "BERGEPAIN.NS\n" +
                        "BFINVEST.NS\n" +
                        "BHAGWATIH.NS\n" +
                        "BHAGYNAGA.NS\n" +
                        "BHARATFOR.NS\n" +
                        "BHARATRAS.NS\n" +
                        "BHARTISHI.NS\n" +
                        "BIL.NS\n" +
                        "BIMETAL.NS\n" +
                        "BINANIIND.NS\n" +
                        "BIRLACORP.NS\n" +
                        "BIRLAERIC.NS\n" +
                        "BIRLAMONE.NS\n" +
                        "BIRLAPOWE.NS\n" +
                        "BLISSGVS.NS\n" +
                        "BLKASHYAP.NS\n" +
                        "BLUECHIP.NS\n" +
                        "BLUEDART.NS\n" +
                        "BLUESTARC.NS\n" +
                        "BLUESTINF.NS\n" +
                        "BOC.NS\n" +
                        "BPL.NS\n" +
                        "BRANDHOUS.NS\n" +
                        "BRFL.NS\n" +
                        "BRIGADE.NS\n" +
                        "BRITANNIA.NS\n" +
                        "BSELINFRA.NS\n" +
                        "BSLGOLDET.NS\n" +
                        "BSLNIFTY.NS\n" +
                        "BSTRANSCO.NS\n" +
                        "BURNPUR.NS\n" +
                        "CADILAHC.NS\n" +
                        "CANDC.NS\n" +
                        "CANFINHOM.NS\n" +
                        "CANTABIL.NS\n" +
                        "CARBORUNI.NS\n" +
                        "CAREERP.NS\n" +
                        "CASTROL.NS\n" +
                        "CCL.NS\n" +
                        "CEATLTD.NS\n" +
                        "CEBBCO.NS\n" +
                        "CENTENKA.NS\n" +
                        "CENTEXT.NS\n" +
                        "CENTUM.NS\n" +
                        "CENTURYPL.NS\n" +
                        "CERA.NS\n" +
                        "CHEMFALKA.NS\n" +
                        "CHENNPETR.NS\n" +
                        "CHETTINAD.NS\n" +
                        "CHOLAFIN.NS\n" +
                        "CHROMATIC.NS\n" +
                        "CILNOVA.NS\n" +
                        "CIMMCO.NS\n" +
                        "CINEPRO.NS\n" +
                        "CLASSIC.NS\n" +
                        "CLNINDIA.NS\n" +
                        "CMAHENDRA.NS\n" +
                        "COMPUAGE.NS\n" +
                        "COMPUSOFT.NS\n" +
                        "CONCOR.NS\n" +
                        "CONSOFINV.NS\n" +
                        "CORDSCABL.NS\n" +
                        "COROMANDE.NS\n" +
                        "CORPBANK.NS\n" +
                        "COSMOFILM.NS\n" +
                        "COX&KINGS.NS\n" +
                        "CREATIVEY.NS\n" +
                        "CRESTANI.NS\n" +
                        "CREWBOS.NS\n" +
                        "CRISIL.NS\n" +
                        "CRMFGETF.NS\n" +
                        "CUB.NS\n" +
                        "CYBERTECH.NS\n" +
                        "DAAWAT.NS\n" +
                        "DALMIABEL.NS\n" +
                        "DALMIASUG.NS\n" +
                        "DATAMATIC.NS\n" +
                        "DBCORP.NS\n" +
                        "DBSTOCKBR.NS\n" +
                        "DCHL.NS\n" +
                        "DCMSRMCON.NS\n" +
                        "DCW.NS\n" +
                        "DECCANCE.NS\n" +
                        "DEEPAKFER.NS\n" +
                        "DEEPAKNTR.NS\n" +
                        "DEEPIND.NS\n" +
                        "DEN.NS\n" +
                        "DENORA.NS\n" +
                        "DENSO.NS\n" +
                        "DHAMPURSU.NS\n" +
                        "DHANBANK.NS\n" +
                        "DHANUKA.NS\n" +
                        "DHARSUGAR.NS\n" +
                        "DHFL.NS\n" +
                        "DIAPOWER.NS\n" +
                        "DICIND.NS\n" +
                        "DIGJAM.NS\n" +
                        "DISHMAN.NS\n" +
                        "DLINKINDI.NS\n" +
                        "DOLPHINOF.NS\n" +
                        "DONEAR.NS\n" +
                        "DPSCLTD.NS\n" +
                        "DPTL.NS\n" +
                        "DQE.NS\n" +
                        "DREDGECOR.NS\n" +
                        "DSKULKARN.NS\n" +
                        "DUNCANSIN.NS\n" +
                        "DYNAMATEC.NS\n" +
                        "EASTSILK.NS\n" +
                        "ECEIND.NS\n" +
                        "EDELWEISS.NS\n" +
                        "EDL.NS\n" +
                        "EICHERMOT.NS\n" +
                        "EIDPARRY.NS\n" +
                        "EIHAHOTEL.NS\n" +
                        "EIHOTEL.NS\n" +
                        "EIMCOELEC.NS\n" +
                        "EKC.NS\n" +
                        "ELDERPHAR.NS\n" +
                        "ELECON.NS\n" +
                        "ELECTCAST.NS\n" +
                        "ELECTCAST.NS\n" +
                        "ELFORGE.NS\n" +
                        "ELGIEQUIP.NS\n" +
                        "ELGIRUBCO.NS\n" +
                        "EMAMILTD.NS\n" +
                        "EMCO.NS\n" +
                        "EMMBI.NS\n" +
                        "ENERGYDEV.NS\n" +
                        "ENGINERSI.NS\n" +
                        "ENIL.NS\n" +
                        "EON.NS\n" +
                        "ERAINFRA.NS\n" +
                        "EROSMEDIA.NS\n" +
                        "ESABINDIA.NS\n" +
                        "ESL.NS\n" +
                        "ESSARPORT.NS\n" +
                        "ESSARSHPN.NS\n" +
                        "ESSDEE.NS\n" +
                        "ESSELPACK.NS\n" +
                        "ESTER.NS\n" +
                        "EUROMULTI.NS\n" +
                        "EUROTEXIN.NS\n" +
                        "EVEREADY.NS\n" +
                        "EVERESTIN.NS\n" +
                        "EVERONN.NS\n" +
                        "EXCELCROP.NS\n" +
                        "EXCELINDU.NS\n" +
                        "EXCELINFO.NS\n" +
                        "FACT.NS\n" +
                        "FAGBEARIN.NS\n" +
                        "FCH.NS\n" +
                        "FDC.NS\n" +
                        "FEDDERLOY.NS\n" +
                        "FIEMIND.NS\n" +
                        "FILATEX.NS\n" +
                        "FINCABLES.NS\n" +
                        "FINPIPE.NS\n" +
                        "FIRSTLEAS.NS\n" +
                        "FIRSTWIN.NS\n" +
                        "FKONCO.NS\n" +
                        "FLEXITUFF.NS\n" +
                        "FMGOETZE.NS\n" +
                        "FMNL.NS\n" +
                        "FOSECOIND.NS\n" +
                        "FOURSOFT.NS\n" +
                        "FSL.NS\n" +
                        "FUTUREVEN.NS\n" +
                        "GABRIEL.NS\n" +
                        "GAEL.NS\n" +
                        "GAL.NS\n" +
                        "GALLANTT.NS\n" +
                        "GALLISPAT.NS\n" +
                        "GAMMNINFR.NS\n" +
                        "GAMMONIND.NS\n" +
                        "GANDHITUB.NS\n" +
                        "GANESHHOU.NS\n" +
                        "GARDENSIL.NS\n" +
                        "GARWALLRO.NS\n" +
                        "GATI.NS\n" +
                        "GAYAPROJ.NS\n" +
                        "GDL.NS\n" +
                        "GEECEE.NS\n" +
                        "GEINDSYS.NS\n" +
                        "GEMINI.NS\n" +
                        "GENESYS.NS\n" +
                        "GENUSPOWE.NS\n" +
                        "GEODESIC.NS\n" +
                        "GEOJITBNP.NS\n" +
                        "GEOMETRIC.NS\n" +
                        "GHCL.NS\n" +
                        "GICHSGFIN.NS\n" +
                        "GILLANDER.NS\n" +
                        "GILLETTE.NS\n" +
                        "GINNIFILA.NS\n" +
                        "GIPCL.NS\n" +
                        "GITANJALI.NS\n" +
                        "GLENMARK.NS\n" +
                        "GLOBALVEC.NS\n" +
                        "GLOBOFFS.NS\n" +
                        "GLOBUSSPR.NS\n" +
                        "GLODYNE.NS\n" +
                        "GLORY.NS\n" +
                        "GMBREW.NS\n" +
                        "GNFC.NS\n" +
                        "GOACARBON.NS\n" +
                        "GODFRYPHL.NS\n" +
                        "GODREJCP.NS\n" +
                        "GODREJPRO.NS\n" +
                        "GOENKA.NS\n" +
                        "GOKEX.NS\n" +
                        "GOKUL.NS\n" +
                        "GOLDBEES.NS\n" +
                        "GOLDIAM.NS\n" +
                        "GOLDINFRA.NS\n" +
                        "GOLDSHARE.NS\n" +
                        "GOLDTECH.NS\n" +
                        "GPIL.NS\n" +
                        "GPPL.NS\n" +
                        "GRANULES.NS\n" +
                        "GRAPHITE.NS\n" +
                        "GRAVITA.NS\n" +
                        "GREAVESCO.NS\n" +
                        "GREENPLY.NS\n" +
                        "GREENPOWE.NS\n" +
                        "GRINDWELL.NS\n" +
                        "GRUH.NS\n" +
                        "GSFC.NS\n" +
                        "GSKCONS.NS\n" +
                        "GSLNOVA.NS\n" +
                        "GSS.NS\n" +
                        "GTL.NS\n" +
                        "GTLINFRA.NS\n" +
                        "GTOFFSHOR.NS\n" +
                        "GUJALKALI.NS\n" +
                        "GUJAPOLLO.NS\n" +
                        "GUJNRECOK.NS\n" +
                        "GUJNRECOK.NS\n" +
                        "GUJNREDVR.NS\n" +
                        "GUJRATGAS.NS\n" +
                        "GUJSIDHCE.NS\n" +
                        "GULFOILCO.NS\n" +
                        "HANUNG.NS\n" +
                        "HARITASEA.NS\n" +
                        "HARRMALAY.NS\n" +
                        "HATHWAY.NS\n" +
                        "HCIL.NS\n" +
                        "HDFC.NS\n" +
                        "HDFCMFGET.NS\n" +
                        "HEG.NS\n" +
                        "HEIDELBER.NS\n" +
                        "HELIOSMAT.NS\n" +
                        "HERCULES.NS\n" +
                        "HERITGFOO.NS\n" +
                        "HFCL.NS\n" +
                        "HGS.NS\n" +
                        "HIKAL.NS\n" +
                        "HIMATSEID.NS\n" +
                        "HINDCOMPO.NS\n" +
                        "HINDCOPPE.NS\n" +
                        "HINDNATGL.NS\n" +
                        "HINDUJAFO.NS\n" +
                        "HINDUJAVE.NS\n" +
                        "HIRAFERRO.NS\n" +
                        "HIRECT.NS\n" +
                        "HITECHGEA.NS\n" +
                        "HITECHPLA.NS\n" +
                        "HMT.NS\n" +
                        "HMVL.NS\n" +
                        "HNGSNGBEE.NS\n" +
                        "HOCL.NS\n" +
                        "HONAUT.NS\n" +
                        "HONDAPOWE.NS\n" +
                        "HORIZONIN.NS\n" +
                        "HOTELEELA.NS\n" +
                        "HOVS.NS\n" +
                        "HSIL.NS\n" +
                        "HTMEDIA.NS\n" +
                        "HUBTOWN.NS\n" +
                        "HYDRBADIN.NS\n" +
                        "HYDROS&S.NS\n" +
                        "IBPOW.NS\n" +
                        "ICRA.NS\n" +
                        "ICSA.NS\n" +
                        "IDBIGOLD.NS\n" +
                        "IFBIND.NS\n" +
                        "IFGLREFRA.NS\n" +
                        "IGARASHI.NS\n" +
                        "IIFLNIFTY.NS\n" +
                        "IL&FSENGG.NS\n" +
                        "IL&FSTRAN.NS\n" +
                        "IMFA.NS\n" +
                        "IMPAL.NS\n" +
                        "INDBANK.NS\n" +
                        "INDIABULL.NS\n" +
                        "INDIABULL.NS\n" +
                        "INDIAGLYC.NS\n" +
                        "INDIANHUM.NS\n" +
                        "INDLMETER.NS\n" +
                        "INDNIPPON.NS\n" +
                        "INDOCO.NS\n" +
                        "INDORAMA.NS\n" +
                        "INDOTECH.NS\n" +
                        "INDOTHAI.NS\n" +
                        "INDOWIND.NS\n" +
                        "INDRAMEDC.NS\n" +
                        "INDSWFTLA.NS\n" +
                        "INDSWFTLT.NS\n" +
                        "INDTERRAI.NS\n" +
                        "INDUSFILA.NS\n" +
                        "INFOMEDIA.NS\n" +
                        "INFOTECEN.NS\n" +
                        "INFRABEES.NS\n" +
                        "INGERRAND.NS\n" +
                        "INGVYSYAB.NS\n" +
                        "INNOIND.NS\n" +
                        "INOXLEISU.NS\n" +
                        "INSECTICI.NS\n" +
                        "IOLCP.NS\n" +
                        "IPCALAB.NS\n" +
                        "IPGETF.NS\n" +
                        "IPRINGLTD.NS\n" +
                        "ISFT.NS\n" +
                        "ISMTLTD.NS\n" +
                        "ITDCEM.NS\n" +
                        "ITI.NS\n" +
                        "IVC.NS\n" +
                        "J&KBANK.NS\n" +
                        "JAGRAN.NS\n" +
                        "JAGSNPHAR.NS\n" +
                        "JAICORPLT.NS\n" +
                        "JAIHINDPR.NS\n" +
                        "JAMNAAUTO.NS\n" +
                        "JAYAGROGN.NS\n" +
                        "JAYBARMAR.NS\n" +
                        "JAYNECOIN.NS\n" +
                        "JAYSREETE.NS\n" +
                        "JBCHEPHAR.NS\n" +
                        "JBFIND.NS\n" +
                        "JBMA.NS\n" +
                        "JENSONICO.NS\n" +
                        "JHS.NS\n" +
                        "JINDALPHO.NS\n" +
                        "JINDALPOL.NS\n" +
                        "JINDALSWH.NS\n" +
                        "JINDCOT.NS\n" +
                        "JINDRILL.NS\n" +
                        "JISLDVREQ.NS\n" +
                        "JKCEMENT.NS\n" +
                        "JKIL.NS\n" +
                        "JKLAKSHMI.NS\n" +
                        "JKPAPER.NS\n" +
                        "JKTYRE.NS\n" +
                        "JMCPROJEC.NS\n" +
                        "JMFINANCI.NS\n" +
                        "JMTAUTOLT.NS\n" +
                        "JOCIL.NS\n" +
                        "JPINFRATE.NS\n" +
                        "JSL.NS\n" +
                        "JUBILANT.NS\n" +
                        "JUBLINDS.NS\n" +
                        "JUNIORBEE.NS\n" +
                        "JVLAGRO.NS\n" +
                        "JYOTHYLAB.NS\n" +
                        "JYOTISTRU.NS\n" +
                        "JYOTISTRU.NS\n" +
                        "KABRAEXTR.NS\n" +
                        "KAJARIACE.NS\n" +
                        "KALECONSU.NS\n" +
                        "KALINDEE.NS\n" +
                        "KALPATPOW.NS\n" +
                        "KAMATHOTE.NS\n" +
                        "KANORICHE.NS\n" +
                        "KANSAINER.NS\n" +
                        "KARURVYSY.NS\n" +
                        "KAVVERITE.NS\n" +
                        "KBIL.NS\n" +
                        "KCP.NS\n" +
                        "KCPSUGIND.NS\n" +
                        "KEC.NS\n" +
                        "KECL.NS\n" +
                        "KEI.NS\n" +
                        "KEMROCK.NS\n" +
                        "KERNEX.NS\n" +
                        "KESORAMIN.NS\n" +
                        "KFA.NS\n" +
                        "KGL.NS\n" +
                        "KHAITANEL.NS\n" +
                        "KICL.NS\n" +
                        "KIL.NS\n" +
                        "KILITCH.NS\n" +
                        "KINETICMO.NS\n" +
                        "KIRLOSBRO.NS\n" +
                        "KIRLOSENG.NS\n" +
                        "KIRLOSIND.NS\n" +
                        "KKCL.NS\n" +
                        "KMSUGAR.NS\n" +
                        "KNRCON.NS\n" +
                        "KOHINOOR.NS\n" +
                        "KOKUYOCML.NS\n" +
                        "KOLTEPATI.NS\n" +
                        "KOPRAN.NS\n" +
                        "KOTAKGOLD.NS\n" +
                        "KOTAKNIFT.NS\n" +
                        "KOTAKPSUB.NS\n" +
                        "KOTHARIPE.NS\n" +
                        "KOTHARIPR.NS\n" +
                        "KOUTONS.NS\n" +
                        "KPIT.NS\n" +
                        "KPRMILL.NS\n" +
                        "KRBL.NS\n" +
                        "KSBPUMPS.NS\n" +
                        "KSCL.NS\n" +
                        "KSE.NS\n" +
                        "KSERASERA.NS\n" +
                        "KSL.NS\n" +
                        "KSOILS.NS\n" +
                        "KWALITY.NS\n" +
                        "L&TFH.NS\n" +
                        "LAKPRE.NS\n" +
                        "LAKSHMIEF.NS\n" +
                        "LAKSHMIMI.NS\n" +
                        "LAKSHVILA.NS\n" +
                        "LANCOIN.NS\n" +
                        "LAOPALA.NS\n" +
                        "LAXMIMACH.NS\n" +
                        "LCCINFOTE.NS\n" +
                        "LGBBROSLT.NS\n" +
                        "LGBFORGE.NS\n" +
                        "LLOYDELEN.NS\n" +
                        "LLOYDFIN.NS\n" +
                        "LML.NS\n" +
                        "LOGIXMICR.NS\n" +
                        "LOKESHMAC.NS\n" +
                        "LOTUSEYE.NS\n" +
                        "LOVABLE.NS\n" +
                        "LPDC.NS\n" +
                        "LUMAXIND.NS\n" +
                        "LUMAXTECH.NS\n" +
                        "M&MFIN.NS\n" +
                        "M100.NS\n" +
                        "M50.NS\n" +
                        "MADHAV.NS\n" +
                        "MADHUCON.NS\n" +
                        "MADRASCEM.NS\n" +
                        "MADRASFER.NS\n" +
                        "MAGMA.NS\n" +
                        "MAGNUM.NS\n" +
                        "MAHABANK.NS\n" +
                        "MAHINDFOR.NS\n" +
                        "MAHINDUGI.NS\n" +
                        "MAHLIFE.NS\n" +
                        "MAHSCOOTE.NS\n" +
                        "MAHSEAMLE.NS\n" +
                        "MANAKSIA.NS\n" +
                        "MANALIPET.NS\n" +
                        "MANDHANA.NS\n" +
                        "MANGALAM.NS\n" +
                        "MANGCHEFE.NS\n" +
                        "MANGTIMBE.NS\n" +
                        "MANINDS.NS\n" +
                        "MANINFRA.NS\n" +
                        "MANJEERA.NS\n" +
                        "MANJUSHRE.NS\n" +
                        "MANUGRAPH.NS\n" +
                        "MARG.NS\n" +
                        "MARICO.NS\n" +
                        "MASTEK.NS\n" +
                        "MAXWELL.NS\n" +
                        "MBECL.NS\n" +
                        "MBLINFRA.NS\n" +
                        "MCX.NS\n" +
                        "MEGASOFT.NS\n" +
                        "MEGH.NS\n" +
                        "MERCATOR.NS\n" +
                        "MERCK.NS\n" +
                        "METKORE.NS\n" +
                        "MGOLD.NS\n" +
                        "MHRIL.NS\n" +
                        "MIC.NS\n" +
                        "MICROSEC.NS\n" +
                        "MICROTECH.NS\n" +
                        "MINDAIND.NS\n" +
                        "MIRCELECT.NS\n" +
                        "MIRZAINT.NS\n" +
                        "MMFL.NS\n" +
                        "MMFSL.NS\n" +
                        "MMTC.NS\n" +
                        "MOIL.NS\n" +
                        "MONNETISP.NS\n" +
                        "MONSANTO.NS\n" +
                        "MOREPENLA.NS\n" +
                        "MOSERBAER.NS\n" +
                        "MOTHERSUM.NS\n" +
                        "MOTILALOF.NS\n" +
                        "MOTOGENFI.NS\n" +
                        "MPSLTD.NS\n" +
                        "MRO-TEK.NS\n" +
                        "MSPL.NS\n" +
                        "MTEDUCARE.NS\n" +
                        "MUKANDENG.NS\n" +
                        "MUKANDLTD.NS\n" +
                        "MUKTAARTS.NS\n" +
                        "MUNJALSHO.NS\n" +
                        "MURLIIND.NS\n" +
                        "MURUDCERA.NS\n" +
                        "MUTHOOTFI.NS\n" +
                        "MVL.NS\n" +
                        "MVLIND.NS\n" +
                        "MYSOREBAN.NS\n" +
                        "N100.NS\n" +
                        "NAGREEKEX.NS\n" +
                        "NAHARCAP.NS\n" +
                        "NAHARINDU.NS\n" +
                        "NAHARPOLY.NS\n" +
                        "NAHARSPIN.NS\n" +
                        "NANDANEXI.NS\n" +
                        "NATCOPHAR.NS\n" +
                        "NATHSEED.NS\n" +
                        "NATIONALU.NS\n" +
                        "NATNLSTEE.NS\n" +
                        "NAVINFLUO.NS\n" +
                        "NAVNETPUB.NS\n" +
                        "NBCC.NS\n" +
                        "NBVENTURE.NS\n" +
                        "NDTV.NS\n" +
                        "NECLIFE.NS\n" +
                        "NELCAST.NS\n" +
                        "NELCO.NS\n" +
                        "NEPCMICON.NS\n" +
                        "NESCO.NS\n" +
                        "NESTLEIND.NS\n" +
                        "NET4.NS\n" +
                        "NETWORK18.NS\n" +
                        "NEXTMEDIA.NS\n" +
                        "NEYVELILI.NS\n" +
                        "NFL.NS\n" +
                        "NICCO.NS\n" +
                        "NIFTYBEES.NS\n" +
                        "NIITLTD.NS\n" +
                        "NIITTECH.NS\n" +
                        "NILKAMAL.NS\n" +
                        "NIPPOBATR.NS\n" +
                        "NITCO.NS\n" +
                        "NITESHEST.NS\n" +
                        "NITINFIRE.NS\n" +
                        "NITINSPIN.NS\n" +
                        "NOCIL.NS\n" +
                        "NOIDATOLL.NS\n" +
                        "NORBTEAEX.NS\n" +
                        "NRBBEARIN.NS\n" +
                        "NRC.NS\n" +
                        "NUCLEUS.NS\n" +
                        "OBEROIRLT.NS\n" +
                        "OCL.NS\n" +
                        "OILCOUNTU.NS\n" +
                        "OISL.NS\n" +
                        "OMAXAUTO.NS\n" +
                        "OMAXE.NS\n" +
                        "OMKARCHEM.NS\n" +
                        "OMMETALS.NS\n" +
                        "OMNITECH.NS\n" +
                        "ONELIFECA.NS\n" +
                        "ONWARDTEC.NS\n" +
                        "ORBITCORP.NS\n" +
                        "ORIENTABR.NS\n" +
                        "ORIENTALT.NS\n" +
                        "ORIENTBEL.NS\n" +
                        "ORIENTHOT.NS\n" +
                        "ORIENTLTD.NS\n" +
                        "ORIENTPPR.NS\n" +
                        "ORIENTREF.NS\n" +
                        "ORISSAMIN.NS\n" +
                        "PAEL.NS\n" +
                        "PAGEIND.NS\n" +
                        "PANACEABI.NS\n" +
                        "PANAMAPET.NS\n" +
                        "PANCARBON.NS\n" +
                        "PANORAMUN.NS\n" +
                        "PAPERPROD.NS\n" +
                        "PARABDRUG.NS\n" +
                        "PARACABLE.NS\n" +
                        "PARAPRINT.NS\n" +
                        "PARASPETR.NS\n" +
                        "PARSVNATH.NS\n" +
                        "PATINTLOG.NS\n" +
                        "PDPL.NS\n" +
                        "PDUMJEPUL.NS\n" +
                        "PENIND.NS\n" +
                        "PENINLAND.NS\n" +
                        "PERSISTEN.NS\n" +
                        "PETRONENG.NS\n" +
                        "PFIZER.NS\n" +
                        "PFOCUS.NS\n" +
                        "PFS.NS\n" +
                        "PGHH.NS\n" +
                        "PHILIPCAR.NS\n" +
                        "PHOENIXLT.NS\n" +
                        "PIDILITIN.NS\n" +
                        "PIIND.NS\n" +
                        "PIPAVAVDO.NS\n" +
                        "PIRGLASS.NS\n" +
                        "PITTILAM.NS\n" +
                        "PLASTIBLE.NS\n" +
                        "PLETHICO.NS\n" +
                        "PNBGILTS.NS\n" +
                        "PNC.NS\n" +
                        "POCHIRAJU.NS\n" +
                        "POLYMED.NS\n" +
                        "POLYPLEX.NS\n" +
                        "PONDYOXID.NS\n" +
                        "PONNIEROD.NS\n" +
                        "PPAP.NS\n" +
                        "PRADIP.NS\n" +
                        "PRAKASH.NS\n" +
                        "PRAKASHCO.NS\n" +
                        "PRAKASHST.NS\n" +
                        "PRATIBHA.NS\n" +
                        "PRECOT.NS\n" +
                        "PRECWIRE.NS\n" +
                        "PREMIER.NS\n" +
                        "PRESTIGE.NS\n" +
                        "PRETAILDV.NS\n" +
                        "PRIMESECU.NS\n" +
                        "PRISMCEM.NS\n" +
                        "PRITHVI.NS\n" +
                        "PSB.NS\n" +
                        "PSL.NS\n" +
                        "PSUBNKBEE.NS\n" +
                        "PTL.NS\n" +
                        "PUNJABCHE.NS\n" +
                        "PURVA.NS\n" +
                        "PVR.NS\n" +
                        "QGOLDHALF.NS\n" +
                        "QNIFTY.NS\n" +
                        "RADAAN.NS\n" +
                        "RADICO.NS\n" +
                        "RAINBOWPA.NS\n" +
                        "RAINCOM.NS\n" +
                        "RAJESHEXP.NS\n" +
                        "RAJOIL.NS\n" +
                        "RAJPALAYA.NS\n" +
                        "RAJTV.NS\n" +
                        "RAJVIR.NS\n" +
                        "RALLIS.NS\n" +
                        "RAMANEWS.NS\n" +
                        "RAMCOIND.NS\n" +
                        "RAMCOSYS.NS\n" +
                        "RAMSARUP.NS\n" +
                        "RANEENGIN.NS\n" +
                        "RANEHOLDI.NS\n" +
                        "RATNAMANI.NS\n" +
                        "RBL.NS\n" +
                        "RBN.NS\n" +
                        "RCF.NS\n" +
                        "REDINGTON.NS\n" +
                        "REIAGROLT.NS\n" +
                        "RELAXO.NS\n" +
                        "RELBANK.NS\n" +
                        "RELGOLD.NS\n" +
                        "RELGRNIFT.NS\n" +
                        "RELIGARE.NS\n" +
                        "RELIGAREG.NS\n" +
                        "RELMEDIA.NS\n" +
                        "REPRO.NS\n" +
                        "RESPONIND.NS\n" +
                        "REVATHI.NS\n" +
                        "RICOAUTO.NS\n" +
                        "RIIL.NS\n" +
                        "RJL.NS\n" +
                        "RKDL.NS\n" +
                        "RKFORGE.NS\n" +
                        "RMCL.NS\n" +
                        "RML.NS\n" +
                        "ROHITFERR.NS\n" +
                        "ROHLTD.NS\n" +
                        "ROMAN.NS\n" +
                        "RPPINFRA.NS\n" +
                        "RSYSTEMS.NS\n" +
                        "RUBYMILLS.NS\n" +
                        "RUCHINFRA.NS\n" +
                        "RUCHIRA.NS\n" +
                        "RUPA.NS\n" +
                        "RUSHIL.NS\n" +
                        "SABTN.NS\n" +
                        "SADBHAV.NS\n" +
                        "SAGCEM.NS\n" +
                        "SAHPETRO.NS\n" +
                        "SAKSOFT.NS\n" +
                        "SAKUMA.NS\n" +
                        "SALORAINT.NS\n" +
                        "SALSTEEL.NS\n" +
                        "SAMBANDAM.NS\n" +
                        "SANDESH.NS\n" +
                        "SANGAMIND.NS\n" +
                        "SANGHIIND.NS\n" +
                        "SANGHVIFO.NS\n" +
                        "SANGHVIMO.NS\n" +
                        "SANOFI.NS\n" +
                        "SARDAEN.NS\n" +
                        "SAREGAMA.NS\n" +
                        "SARLAPOLY.NS\n" +
                        "SASKEN.NS\n" +
                        "SATHAISPA.NS\n" +
                        "SATYAMCOM.NS\n" +
                        "SAVERA.NS\n" +
                        "SB&TINTL.NS\n" +
                        "SBBJ.NS\n" +
                        "SBIGETS.NS\n" +
                        "SBT.NS\n" +
                        "SCHNEIDER.NS\n" +
                        "SEAMECLTD.NS\n" +
                        "SEINV.NS\n" +
                        "SELAN.NS\n" +
                        "SERVALL.NS\n" +
                        "SESHAPAPE.NS\n" +
                        "SGJHL.NS\n" +
                        "SHAKTIPUM.NS\n" +
                        "SHARIABEE.NS\n" +
                        "SHARONBIO.NS\n" +
                        "SHARRESLT.NS\n" +
                        "SHASUNPHA.NS\n" +
                        "SHILPAMED.NS\n" +
                        "SHIV-VANI.NS\n" +
                        "SHLAKSHMI.NS\n" +
                        "SHOPERSTO.NS\n" +
                        "SHREEASHT.NS\n" +
                        "SHREECEM.NS\n" +
                        "SHREERAMA.NS\n" +
                        "SHRENUJ.NS\n" +
                        "SHRIRAMCI.NS\n" +
                        "SHRIRAMEP.NS\n" +
                        "SHYAMTEL.NS\n" +
                        "SICAGEN.NS\n" +
                        "SICAL.NS\n" +
                        "SIGNETIND.NS\n" +
                        "SILINV.NS\n" +
                        "SIMPLEX.NS\n" +
                        "SIMPLEXIN.NS\n" +
                        "SIRPAPER.NS\n" +
                        "SITASHREE.NS\n" +
                        "SIYSIL.NS\n" +
                        "SJVN.NS\n" +
                        "SKFINDIA.NS\n" +
                        "SKMEGGPRO.NS\n" +
                        "SKSMICRO.NS\n" +
                        "SMARTLINK.NS\n" +
                        "SMLISUZU.NS\n" +
                        "SMPL.NS\n" +
                        "SMSPHARMA.NS\n" +
                        "SOFTTECHG.NS\n" +
                        "SOLARINDS.NS\n" +
                        "SOMANYCER.NS\n" +
                        "SONASTEER.NS\n" +
                        "SONATSOFT.NS\n" +
                        "SOTL.NS\n" +
                        "SOUISPAT.NS\n" +
                        "SPANCO.NS\n" +
                        "SPARC.NS\n" +
                        "SPECIALIT.NS\n" +
                        "SPECTACLE.NS\n" +
                        "SPIC.NS\n" +
                        "SPMLINFRA.NS\n" +
                        "SRF.NS\n" +
                        "SRHHLINDS.NS\n" +
                        "SRSLTD.NS\n" +
                        "SSWL.NS\n" +
                        "STAN.NS\n" +
                        "STAR.NS\n" +
                        "STCINDIA.NS\n" +
                        "STEL.NS\n" +
                        "STERTOOLS.NS\n" +
                        "STYABS.NS\n" +
                        "SUBEX.NS\n" +
                        "SUBROS.NS\n" +
                        "SUDAR.NS\n" +
                        "SUDARSCHE.NS\n" +
                        "SUJANAUNI.NS\n" +
                        "SUMEETIND.NS\n" +
                        "SUMMITSEC.NS\n" +
                        "SUNCLAYTO.NS\n" +
                        "SUNDARAM.NS\n" +
                        "SUNDARMFI.NS\n" +
                        "SUNDRMBRA.NS\n" +
                        "SUNDRMFAS.NS\n" +
                        "SUNFLAG.NS\n" +
                        "SUNILHITE.NS\n" +
                        "SUNTECK.NS\n" +
                        "SUPER.NS\n" +
                        "SUPPETRO.NS\n" +
                        "SUPRAJIT.NS\n" +
                        "SUPREMEIN.NS\n" +
                        "SUPREMEIN.NS\n" +
                        "SURAJDIAM.NS\n" +
                        "SURANAIND.NS\n" +
                        "SURANAT&P.NS\n" +
                        "SURANAVEL.NS\n" +
                        "SURYALAXM.NS\n" +
                        "SURYAROSN.NS\n" +
                        "SUTLEJTEX.NS\n" +
                        "SUVEN.NS\n" +
                        "SWANENERG.NS\n" +
                        "SWARAJENG.NS\n" +
                        "SYMPHONY.NS\n" +
                        "SYNCOM.NS\n" +
                        "TAJGVK.NS\n" +
                        "TALBROAUT.NS\n" +
                        "TALWALKAR.NS\n" +
                        "TANLA.NS\n" +
                        "TANTIACON.NS\n" +
                        "TATAELXSI.NS\n" +
                        "TATAINVES.NS\n" +
                        "TATAMETAL.NS\n" +
                        "TATASPONG.NS\n" +
                        "TBZ.NS\n" +
                        "TCI.NS\n" +
                        "TCIDEVELO.NS\n" +
                        "TDPOWERSY.NS\n" +
                        "TECHNO.NS\n" +
                        "TECHNOFAB.NS\n" +
                        "TECPRO.NS\n" +
                        "TEXINFRA.NS\n" +
                        "TEXRAIL.NS\n" +
                        "TFCILTD.NS\n" +
                        "THANGAMAY.NS\n" +
                        "THEBYKE.NS\n" +
                        "THEMISMED.NS\n" +
                        "THERMAX.NS\n" +
                        "THOMASCOO.NS\n" +
                        "TI.NS\n" +
                        "TIDEWATER.NS\n" +
                        "TIIL.NS\n" +
                        "TIJARIA.NS\n" +
                        "TIL.NS\n" +
                        "TIMBOR.NS\n" +
                        "TIMETECHN.NS\n" +
                        "TIMKEN.NS\n" +
                        "TINPLATE.NS\n" +
                        "TIPSINDLT.NS\n" +
                        "TNPETRO.NS\n" +
                        "TNPL.NS\n" +
                        "TODAYS.NS\n" +
                        "TOKYOPLAS.NS\n" +
                        "TORNTPHAR.NS\n" +
                        "TORNTPOWE.NS\n" +
                        "TREEHOUSE.NS\n" +
                        "TRENT.NS\n" +
                        "TRF.NS\n" +
                        "TRIDENT.NS\n" +
                        "TRIGYN.NS\n" +
                        "TRIL.NS\n" +
                        "TRITURBIN.NS\n" +
                        "TRIVENI.NS\n" +
                        "TTKHEALTH.NS\n" +
                        "TUBEINVES.NS\n" +
                        "TULSI.NS\n" +
                        "TULSYAN.NS\n" +
                        "TV18BRDCS.NS\n" +
                        "TVSELECT.NS\n" +
                        "TVSSRICHA.NS\n" +
                        "TVTODAY.NS\n" +
                        "TWILITAKA.NS\n" +
                        "TWL.NS\n" +
                        "UBENGG.NS\n" +
                        "UBHOLDING.NS\n" +
                        "UBL.NS\n" +
                        "UCALFUEL.NS\n" +
                        "UFLEX.NS\n" +
                        "UGARSUGAR.NS\n" +
                        "UNICHEMLA.NS\n" +
                        "UNIENTER.NS\n" +
                        "UNITEDBNK.NS\n" +
                        "UNITY.NS\n" +
                        "UNIVCABLE.NS\n" +
                        "USHAMART.NS\n" +
                        "USHERAGRO.NS\n" +
                        "UTTAMSTL.NS\n" +
                        "VADILALIN.NS\n" +
                        "VAIBHAVGE.NS\n" +
                        "VAKRANSOF.NS\n" +
                        "VALECHAEN.NS\n" +
                        "VALUEIND.NS\n" +
                        "VARDHACRL.NS\n" +
                        "VARUNSHIP.NS\n" +
                        "VASCONEQ.NS\n" +
                        "VASWANI.NS\n" +
                        "VENKEYS.NS\n" +
                        "VENUSREM.NS\n" +
                        "VESUVIUS.NS\n" +
                        "VGUARD.NS\n" +
                        "VHL.NS\n" +
                        "VIKASGLOB.NS\n" +
                        "VINATIORG.NS\n" +
                        "VINDHYATE.NS\n" +
                        "VIPUL.NS\n" +
                        "VISAKAIND.NS\n" +
                        "VISASTEEL.NS\n" +
                        "VISESHINF.NS\n" +
                        "VISUINTL.NS\n" +
                        "VIVIMEDLA.NS\n" +
                        "VOLTAMP.NS\n" +
                        "VSSL.NS\n" +
                        "VSTIND.NS\n" +
                        "VSTTILLER.NS\n" +
                        "VTL.NS\n" +
                        "VTXIND.NS\n" +
                        "WABAG.NS\n" +
                        "WABCOINDI.NS\n" +
                        "WENDT.NS\n" +
                        "WHEELS.NS\n" +
                        "WHIRLPOOL.NS\n" +
                        "WILLAMAGO.NS\n" +
                        "WOCKPHARM.NS\n" +
                        "WSTCSTPAP.NS\n" +
                        "WYETH.NS\n" +
                        "XCHANGING.NS\n" +
                        "XLENERGY.NS\n" +
                        "XPROINDIA.NS\n" +
                        "ZANDUREAL.NS\n" +
                        "ZENITHBIR.NS\n" +
                        "ZENITHINF.NS\n" +
                        "ZENSARTEC.NS\n" +
                        "ZICOM.NS\n" +
                        "ZODIACLOT.NS\n" +
                        "ZUARIAGRO.NS\n" +
                        "ZYDUSWELL.NS\n" +
                        "ZYLOG.NS\n" +
                        "ABAN.NS\n" +
                        "ABB.NS\n" +
                        "ABIRLANUV.NS\n" +
                        "ACC.NS\n" +
                        "ADANIENT.NS\n" +
                        "ADANIPORT.NS\n" +
                        "ADANIPOWE.NS\n" +
                        "AIL.NS\n" +
                        "ALBK.NS\n" +
                        "ALOKTEXT.NS\n" +
                        "AMBUJACEM.NS\n" +
                        "ANDHRABAN.NS\n" +
                        "APOLLOTYR.NS\n" +
                        "ARVIND.NS\n" +
                        "ASHOKLEY.NS\n" +
                        "ASIANPAIN.NS\n" +
                        "AUROPHARM.NS\n" +
                        "AXISBANK.NS\n" +
                        "BAJAJ-AUT.NS\n" +
                        "BAJAJHIND.NS\n" +
                        "BAJAJHLDN.NS\n" +
                        "BALRAMCHI.NS\n" +
                        "BANKBAROD.NS\n" +
                        "BANKINDIA.NS\n" +
                        "BATAINDIA.NS\n" +
                        "BEL.NS\n" +
                        "BEML.NS\n" +
                        "BFUTILITI.NS\n" +
                        "BGRENERGY.NS\n" +
                        "BHARATFOR.NS\n" +
                        "BHARTIART.NS\n" +
                        "BHEL.NS\n" +
                        "BHUSANSTL.NS\n" +
                        "BIOCON.NS\n" +
                        "BOMDYEING.NS\n" +
                        "BOSCHLTD.NS\n" +
                        "BPCL.NS\n" +
                        "CAIRN.NS\n" +
                        "CANBK.NS\n" +
                        "CENTRALBK.NS\n" +
                        "CENTURYTE.NS\n" +
                        "CESC.NS\n" +
                        "CHAMBLFER.NS\n" +
                        "CIPLA.NS\n" +
                        "CMC.NS\n" +
                        "COALINDIA.NS\n" +
                        "COLPAL.NS\n" +
                        "COREEDUTE.NS\n" +
                        "CROMPGREA.NS\n" +
                        "CUMMINSIN.NS\n" +
                        "DABUR.NS\n" +
                        "DCB.NS\n" +
                        "DELTACORP.NS\n" +
                        "DENABANK.NS\n" +
                        "DISHTV.NS\n" +
                        "DIVISLAB.NS\n" +
                        "DLF.NS\n" +
                        "DRREDDY.NS\n" +
                        "ECLERX.NS\n" +
                        "EDUCOMP.NS\n" +
                        "ESCORTS.NS\n" +
                        "ESSAROIL.NS\n" +
                        "EXIDEIND.NS\n" +
                        "FEDERALBN.NS\n" +
                        "FINANTECH.NS\n" +
                        "FORTIS.NS\n" +
                        "GAIL.NS\n" +
                        "GESHIP.NS\n" +
                        "GLAXO.NS\n" +
                        "GMDCLTD.NS\n" +
                        "GMRINFRA.NS\n" +
                        "GODREJIND.NS\n" +
                        "GRASIM.NS\n" +
                        "GSPL.NS\n" +
                        "GUJFLUORO.NS\n" +
                        "GVKPIL.NS\n" +
                        "HAVELLS.NS\n" +
                        "HCC.NS\n" +
                        "HCL-INSYS.NS\n" +
                        "HCLTECH.NS\n" +
                        "HDFC.NS\n" +
                        "HDFCBANK.NS\n" +
                        "HDIL.NS\n" +
                        "HEROMOTOC.NS\n" +
                        "HEXAWARE.NS\n" +
                        "HINDALCO.NS\n" +
                        "HINDOILEX.NS\n" +
                        "HINDPETRO.NS\n" +
                        "HINDUNILV.NS\n" +
                        "HINDZINC.NS\n" +
                        "IBREALEST.NS\n" +
                        "ICICIBANK.NS\n" +
                        "IDBI.NS\n" +
                        "IDEA.NS\n" +
                        "IDFC.NS\n" +
                        "IFCI.NS\n" +
                        "IGL.NS\n" +
                        "INDHOTEL.NS\n" +
                        "INDIACEM.NS\n" +
                        "INDIAINFO.NS\n" +
                        "INDIANB.NS\n" +
                        "INDUSINDB.NS\n" +
                        "INFY.NS\n" +
                        "IOB.NS\n" +
                        "IOC.NS\n" +
                        "IRB.NS\n" +
                        "ITC.NS\n" +
                        "IVRCLINFR.NS\n" +
                        "JETAIRWAY.NS\n" +
                        "JINDALSAW.NS\n" +
                        "JINDALSTE.NS\n" +
                        "JISLJALEQ.NS\n" +
                        "JPASSOCIA.NS\n" +
                        "JPPOWER.NS\n" +
                        "JSWENERGY.NS\n" +
                        "JSWISPAT.NS\n" +
                        "JSWSTEEL.NS\n" +
                        "JUBLFOOD.NS\n" +
                        "KOTAKBANK.NS\n" +
                        "KTKBANK.NS\n" +
                        "LICHSGFIN.NS\n" +
                        "LITL.NS\n" +
                        "LT.NS\n" +
                        "LUPIN.NS\n" +
                        "M&M.NS\n" +
                        "MARUTI.NS\n" +
                        "MAX.NS\n" +
                        "MCDOWELL-.NS\n" +
                        "MCLEODRUS.NS\n" +
                        "MINDTREE.NS\n" +
                        "MPHASIS.NS\n" +
                        "MRF.NS\n" +
                        "MRPL.NS\n" +
                        "MTNL.NS\n" +
                        "NAGAROIL.NS\n" +
                        "NAUKRI.NS\n" +
                        "NCC.NS\n" +
                        "NHPC.NS\n" +
                        "NMDC.NS\n" +
                        "NTPC.NS\n" +
                        "OFSS.NS\n" +
                        "OIL.NS\n" +
                        "ONGC.NS\n" +
                        "ONMOBILE.NS\n" +
                        "OPTOCIRCU.NS\n" +
                        "ORCHIDCHE.NS\n" +
                        "ORIENTBAN.NS\n" +
                        "PANTALOON.NS\n" +
                        "PATELENG.NS\n" +
                        "PETRONET.NS\n" +
                        "PFC.NS\n" +
                        "PIRHEALTH.NS\n" +
                        "PNB.NS\n" +
                        "POLARIS.NS\n" +
                        "POWERGRID.NS\n" +
                        "PRAJIND.NS\n" +
                        "PTC.NS\n" +
                        "PUNJLLOYD.NS\n" +
                        "RANBAXY.NS\n" +
                        "RAYMOND.NS\n" +
                        "RCOM.NS\n" +
                        "RECLTD.NS\n" +
                        "RELCAPITA.NS\n" +
                        "RELIANCE.NS\n" +
                        "RELINFRA.NS\n" +
                        "RENUKA.NS\n" +
                        "ROLTA.NS\n" +
                        "RPOWER.NS\n" +
                        "RUCHISOYA.NS\n" +
                        "SAIL.NS\n" +
                        "SBIN.NS\n" +
                        "SCI.NS\n" +
                        "SESAGOA.NS\n" +
                        "SIEMENS.NS\n" +
                        "SINTEX.NS\n" +
                        "SKUMARSYN.NS\n" +
                        "SOBHA.NS\n" +
                        "SOUTHBANK.NS\n" +
                        "SREINFRA.NS\n" +
                        "SRTRANSFI.NS\n" +
                        "STER.NS\n" +
                        "STRTECH.NS\n" +
                        "SUNPHARMA.NS\n" +
                        "SUNTV.NS\n" +
                        "SUZLON.NS\n" +
                        "SYNDIBANK.NS\n" +
                        "TATACHEM.NS\n" +
                        "TATACOFFE.NS\n" +
                        "TATACOMM.NS\n" +
                        "TATAGLOBA.NS\n" +
                        "TATAMOTOR.NS\n" +
                        "TATAMTRDV.NS\n" +
                        "TATAPOWER.NS\n" +
                        "TATASTEEL.NS\n" +
                        "TCS.NS\n" +
                        "TECHM.NS\n" +
                        "TITAN.NS\n" +
                        "TTKPRESTI.NS\n" +
                        "TTML.NS\n" +
                        "TULIP.NS\n" +
                        "TVSMOTOR.NS\n" +
                        "UCOBANK.NS\n" +
                        "ULTRACEMC.NS\n" +
                        "UNIONBANK.NS\n" +
                        "UNIPHOS.NS\n" +
                        "UNITECH.NS\n" +
                        "VIDEOIND.NS\n" +
                        "VIJAYABAN.NS\n" +
                        "VIPIND.NS\n" +
                        "VOLTAS.NS\n" +
                        "WELCORP.NS\n" +
                        "WIPRO.NS\n" +
                        "YESBANK.NS\n" +
                        "ZEEL.NS\n";
        final String[] tokens = scrips.split("\n");
        return tokens;
    }
}
